service: cvs-svc-test-number

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  generateTestNumber:
    handler: src/handler.handler

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-test-number
        AttributeDefinitions:
        - AttributeName: testNumberKey
          AttributeType: N
        KeySchema:
        - AttributeName: testNumberKey
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  serverless-offline:
    port: 3008
  dynamodb:
    start:
      port: 8008
      inMemory: true
      migrate: false
      seed: false
      noStart: true
    seed:
      test-number:
        sources:
        - table: cvs-local-test-number
          sources: [./tests/resources/test-number.json]
    stages:
      - dev
